//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirService.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirService.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string AccountController_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("AccountController_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent to your registered e-mail account successfully..
        /// </summary>
        public static string AccountController_ForgottenPasswordSuccess {
            get {
                return ResourceManager.GetString("AccountController_ForgottenPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AccountController_Logon_InvalidCredential {
            get {
                return ResourceManager.GetString("AccountController_Logon_InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked due to too many login attempts. Please contact us..
        /// </summary>
        public static string AccountController_LogOn_Locked {
            get {
                return ResourceManager.GetString("AccountController_LogOn_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering with AirService. Please check your email for a confirmation
        ///request with a link that will confirm your account. Once you click the link your
        ///registration will be complete..
        /// </summary>
        public static string AccountController_RegisterSucceeded {
            get {
                return ResourceManager.GetString("AccountController_RegisterSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string APN_ConnectedToVenueArg0 {
            get {
                return ResourceManager.GetString("APN_ConnectedToVenueArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, please see a member of staff.
        /// </summary>
        public static string APN_ConnectionRejectMessage {
            get {
                return ResourceManager.GetString("APN_ConnectionRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} is requesting to close session..
        /// </summary>
        public static string APN_CustomerArg0RequestForClosingSession {
            get {
                return ResourceManager.GetString("APN_CustomerArg0RequestForClosingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New connection request from customer {0}.
        /// </summary>
        public static string APN_NewConnectionRequestFromArg0 {
            get {
                return ResourceManager.GetString("APN_NewConnectionRequestFromArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order from customer {0}.
        /// </summary>
        public static string APN_NewOrderFromCustomerArg0 {
            get {
                return ResourceManager.GetString("APN_NewOrderFromCustomerArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received and is being prepared..
        /// </summary>
        public static string APN_OrderConfirmed {
            get {
                return ResourceManager.GetString("APN_OrderConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is ready and will be with you shortly.
        /// </summary>
        public static string APN_OrderReady {
            get {
                return ResourceManager.GetString("APN_OrderReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is ready for you to pick up now..
        /// </summary>
        public static string APN_OrderReadyForPickup {
            get {
                return ResourceManager.GetString("APN_OrderReadyForPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session at {0} has closed. Thank you..
        /// </summary>
        public static string APN_SessionAtArgs0Closed {
            get {
                return ResourceManager.GetString("APN_SessionAtArgs0Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDID is required..
        /// </summary>
        public static string Err1001UdidRequired {
            get {
                return ResourceManager.GetString("Err1001UdidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name and last name are required..
        /// </summary>
        public static string Err1002FirstNameAndLastNameAreRequired {
            get {
                return ResourceManager.GetString("Err1002FirstNameAndLastNameAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string Err1003CustomerNotFound {
            get {
                return ResourceManager.GetString("Err1003CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. Please try again later..
        /// </summary>
        public static string Err1004UnexpectedError {
            get {
                return ResourceManager.GetString("Err1004UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not available. Please contact customer support..
        /// </summary>
        public static string Err1005CustomerDisabled {
            get {
                return ResourceManager.GetString("Err1005CustomerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested menu &quot;{0}&quot; is not available at this time. Please try again later..
        /// </summary>
        public static string Err1007MenuArg0NotAvailable {
            get {
                return ResourceManager.GetString("Err1007MenuArg0NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All menu items in the requested menu category &quot;{0}&quot; are not available at this time. Please try again later. .
        /// </summary>
        public static string Err1008MenuCategoryArg0NotAvailable {
            get {
                return ResourceManager.GetString("Err1008MenuCategoryArg0NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested menu item &quot;{0}&quot; is not available at this time. Please try again later. .
        /// </summary>
        public static string Err1009MenuItemArg0NotAvailable {
            get {
                return ResourceManager.GetString("Err1009MenuItemArg0NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with the venue already made..
        /// </summary>
        public static string Err1010VenueConnectionAlreadyMade {
            get {
                return ResourceManager.GetString("Err1010VenueConnectionAlreadyMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested venue is temporarily not available..
        /// </summary>
        public static string Err1011VenueTemporarilyNotAvailable {
            get {
                return ResourceManager.GetString("Err1011VenueTemporarilyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested venue is not found..
        /// </summary>
        public static string Err1012VenueNotFound {
            get {
                return ResourceManager.GetString("Err1012VenueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to connect &apos;{0}&apos; ({1}).
        /// </summary>
        public static string Err1013WaitingToConnectToVenueArgs2 {
            get {
                return ResourceManager.GetString("Err1013WaitingToConnectToVenueArgs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID &amp; PIN is already used by another device. .
        /// </summary>
        public static string Err1014DevicePinAlreadyUsedByAnotherDevice {
            get {
                return ResourceManager.GetString("Err1014DevicePinAlreadyUsedByAnotherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; of menu item &quot;{1}&quot; is not available..
        /// </summary>
        public static string Err1015MenuItemOptionArg0OfMenuItemArg1NotAvailable {
            get {
                return ResourceManager.GetString("Err1015MenuItemOptionArg0OfMenuItemArg1NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place the order due to one or more errors..
        /// </summary>
        public static string Err1016FailedToPlaceOrderDueToOneOrMoreItems {
            get {
                return ResourceManager.GetString("Err1016FailedToPlaceOrderDueToOneOrMoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the order because it does not have any order items..
        /// </summary>
        public static string Err1017CannotProcessOrderWithEmptyItems {
            get {
                return ResourceManager.GetString("Err1017CannotProcessOrderWithEmptyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu &quot;{0}&quot; only available between {1} and {2}..
        /// </summary>
        public static string Err1018MenuItemOnlyAvailableBetweenArg0AndArg1 {
            get {
                return ResourceManager.GetString("Err1018MenuItemOnlyAvailableBetweenArg0AndArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        public static string Err1019OrderNotFound {
            get {
                return ResourceManager.GetString("Err1019OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item {0} not found..
        /// </summary>
        public static string Err1020OrderItemArg0NotFound {
            get {
                return ResourceManager.GetString("Err1020OrderItemArg0NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requesting device cannot process the order item {0}.
        /// </summary>
        public static string Err1021TheiPadCannotProcessTheGivenOrderItemArg0 {
            get {
                return ResourceManager.GetString("Err1021TheiPadCannotProcessTheGivenOrderItemArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order item {0} is already being processed..
        /// </summary>
        public static string Err1022OrderItemArg0IsAlreadyBeingProcessed {
            get {
                return ResourceManager.GetString("Err1022OrderItemArg0IsAlreadyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of order item &quot;{0}&quot; is invalid..
        /// </summary>
        public static string Err1023OrderItemArg0PriceMismatch {
            get {
                return ResourceManager.GetString("Err1023OrderItemArg0PriceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is already processed.
        /// </summary>
        public static string Err1024OrderAlreadyProcessed {
            get {
                return ResourceManager.GetString("Err1024OrderAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update order or order item that is cancelled..
        /// </summary>
        public static string Err1025CannotUpdateCancelledOrderOrCancelledOrderItem {
            get {
                return ResourceManager.GetString("Err1025CannotUpdateCancelledOrderOrCancelledOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place an order. Please contact customer service..
        /// </summary>
        public static string Err1025FleezedCustomerCannotMakeAnOrder {
            get {
                return ResourceManager.GetString("Err1025FleezedCustomerCannotMakeAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is not connected to the venue..
        /// </summary>
        public static string Err1026CustomerNotConnected {
            get {
                return ResourceManager.GetString("Err1026CustomerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to connect.
        /// </summary>
        public static string Err1027WaitingToConnectToTheVenue {
            get {
                return ResourceManager.GetString("Err1027WaitingToConnectToTheVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate bill because following order item(s) are not processed.
        ///{0}.
        /// </summary>
        public static string Err1028CannotFinalizeOrderBecauseNotAllOrdersAreComplete {
            get {
                return ResourceManager.GetString("Err1028CannotFinalizeOrderBecauseNotAllOrdersAreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Venue area does not exist or temporarily unavailable..
        /// </summary>
        public static string Err1029VenueAreaNotFoundOrUnavailable {
            get {
                return ResourceManager.GetString("Err1029VenueAreaNotFoundOrUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu not found..
        /// </summary>
        public static string Err1030MenuNotFound {
            get {
                return ResourceManager.GetString("Err1030MenuNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu category not found.
        /// </summary>
        public static string Err1031MenuCategoryNotFound {
            get {
                return ResourceManager.GetString("Err1031MenuCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item not found.
        /// </summary>
        public static string Err1032MenuItemNotFound {
            get {
                return ResourceManager.GetString("Err1032MenuItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify menu status because the device admin is not associated with the menu..
        /// </summary>
        public static string Err1033DeviceAdminCannotChangeMenuIfNotAssociatedWithIt {
            get {
                return ResourceManager.GetString("Err1033DeviceAdminCannotChangeMenuIfNotAssociatedWithIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reject customer’s connection after connection was accepted..
        /// </summary>
        public static string Err1034CannotRejectConnectionOnceConnected {
            get {
                return ResourceManager.GetString("Err1034CannotRejectConnectionOnceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot accept the new order while the customer status is not active..
        /// </summary>
        public static string Err1036CannotPlaceOrderIfNotActiveCustomer {
            get {
                return ResourceManager.GetString("Err1036CannotPlaceOrderIfNotActiveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot request checkout until all your orders have been processed.
        ///
        ///If you have received all your orders, please contact a member of staff..
        /// </summary>
        public static string Err1037CannotCloseConnectionWhenActiveOrdersExist {
            get {
                return ResourceManager.GetString("Err1037CannotCloseConnectionWhenActiveOrdersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot undo order item status. Please refresh your data and try again..
        /// </summary>
        public static string Err1038CannotUndoOrderItemStatus {
            get {
                return ResourceManager.GetString("Err1038CannotUndoOrderItemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad &apos;{0}&apos; has already accepted this order item..
        /// </summary>
        public static string Err1039OrderItemProcessedByAnotheriPadArg1 {
            get {
                return ResourceManager.GetString("Err1039OrderItemProcessedByAnotheriPadArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the requested device or access denied..
        /// </summary>
        public static string Err1040CannotFindDeviceOrAccessDenied {
            get {
                return ResourceManager.GetString("Err1040CannotFindDeviceOrAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have both delivery and pickup option disabled..
        /// </summary>
        public static string Err1041BothDeliveryAndPickupDisabled {
            get {
                return ResourceManager.GetString("Err1041BothDeliveryAndPickupDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service option specified is not valid. If delivery option is chosen, the assigned iPad’s delivery option must be enabled and if pickup option is chosen, pickup option of the assigned iPad must be enabled..
        /// </summary>
        public static string Err1042InvalidOrderItemServiceOption {
            get {
                return ResourceManager.GetString("Err1042InvalidOrderItemServiceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not found..
        /// </summary>
        public static string Err1043EmailNotFound {
            get {
                return ResourceManager.GetString("Err1043EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. Please ensure you have entered correct email address. Please try again later..
        /// </summary>
        public static string Err1044FailedToSendEmail {
            get {
                return ResourceManager.GetString("Err1044FailedToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Notification Token is required..
        /// </summary>
        public static string Err1045RemoteNotificationTokenRequired {
            get {
                return ResourceManager.GetString("Err1045RemoteNotificationTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} messages per {1} hour(s) are allowed..
        /// </summary>
        public static string Err1046BroadcastMessageLimitArg0PerArg1Reached {
            get {
                return ResourceManager.GetString("Err1046BroadcastMessageLimitArg0PerArg1Reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid message length is between 1 and {0} characters..
        /// </summary>
        public static string Err1047MaxMessageLengthArg0 {
            get {
                return ResourceManager.GetString("Err1047MaxMessageLengthArg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This venue cannot be connected due to account type restriction..
        /// </summary>
        public static string Err1048CannotConnectToVenueWhichIsNotFullAccountType {
            get {
                return ResourceManager.GetString("Err1048CannotConnectToVenueWhichIsNotFullAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image file..
        /// </summary>
        public static string Err2001InvalidImageFile {
            get {
                return ResourceManager.GetString("Err2001InvalidImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no transactions.
        /// </summary>
        public static string ErrorNoPaymentTransactions {
            get {
                return ResourceManager.GetString("ErrorNoPaymentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment system is temporary unavailable. Please try again later.
        /// </summary>
        public static string PaymentServerDown {
            get {
                return ResourceManager.GetString("PaymentServerDown", resourceCulture);
            }
        }
    }
}
